image: docker:18.06.3-ce-git

#stages:
#  - build
#  - push
#  - deploy

#variables:
#  TERM: linux
#  DOCKER_HOST: tcp://gitlab-dind-svc:2375
#  DOCKER_DRIVER: overlay2

#before_script:
#  - apk add bash git ncurses openssh

Orchestrator-build: &Orchestrator-build
  stage: build
  script:
    - chmod +x $CI_PROJECT_DIR/Orchestrator/docker/build.sh && $CI_PROJECT_DIR/Orchestrator/docker/build.sh
  only:
    changes:
      - "Orchestrator/**/*"
    refs:
      - branches
    variables:
      - $CI_COMMIT_MESSAGE =~ /ci-build/
  except:
    refs:
      - master
#    variables:
#      - $CI_COMMIT_BEFORE_SHA =~ /^0+$/
  retry: 2
  tags:
    - k8s
#  when: manual

Orchestrator-push: &Orchestrator-push
  stage: push
  script:
    - chmod +x $CI_PROJECT_DIR/Orchestrator/docker/push.sh && $CI_PROJECT_DIR/Orchestrator/docker/push.sh
  only:
    changes:
      - "Orchestrator/**/*"
    refs:
      - branches
    variables:
      - $CI_COMMIT_MESSAGE =~ /ci-build/
  except:
    refs:
      - master
#    variables:
#      - $CI_COMMIT_BEFORE_SHA =~ /^0+$/
  retry: 2
  tags:
    - k8s
#  when: manual

Orchestrator-manual-build:
  <<: *Orchestrator-build
  only:
    - branches
  except:
    refs:
      - master
    variables:
      - $BUILD_VERSION
  when: manual

Orchestrator-manual-push:
  <<: *Orchestrator-push
  only:
    - branches
  except:
    refs:
      - master
    variables:
      - $BUILD_VERSION
  when: manual
#  allow_failure: false

Orchestrator-test-build:
  stage: build
  script:
    - chmod +x $CI_PROJECT_DIR/Orchestrator/docker/build.sh && $CI_PROJECT_DIR/Orchestrator/docker/build.sh
  only:
    refs:
      - branches
    variables:
#      - $CI_COMMIT_REF_NAME =~ /^PACE_2.0.\d+$/
      - $BUILD_VERSION =~ /^\d+$/
  except:
#    - merge_requests
    - master
  retry: 2
  tags:
    - k8s
#  when: manual

Orchestrator-test-push:
  stage: push
  script:
    - chmod +x $CI_PROJECT_DIR/Orchestrator/docker/push.sh && $CI_PROJECT_DIR/Orchestrator/docker/push.sh
  only:
    refs:
      - branches
    variables:
#      - $CI_COMMIT_REF_NAME =~ /^PACE_2.0.\d+$/
      - $BUILD_VERSION =~ /^\d+$/
  except:
#    - merge_requests
    - master
  retry: 2
  tags:
    - k8s
#  when: manual
